src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
class Services
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $url_icon = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getUrlIcon(): ?string
    {
        return $this->url_icon;
    }

    public function setUrlIcon(string $url_icon): static
    {
        $this->url_icon = $url_icon;

        return $this;
    }
}

templates/components/adminList/fifthItem.html.twig
{% block fifthItem %}
<h2>Animaux</h2>
<ul class="animaux-container">
<ul class="habitat-list">

  {% for habitat in habitats %}
    <li>{{ habitat.name }}</li>
  {% endfor %}
 </ul>

  {% for habitat in habitats %}
      <ul class="animal-habitat habitat-{{ loop.index }}" data-id="{{habitat.name}}">
      {% for animal in habitat.animals %}
        <li>{{ animal.name }}</li>
      {% endfor %}
    </ul>
  {% endfor %}
   
</ul>
{% set global_index = 0 %}
{% for habitat in habitats %}
    {% for animal in habitat.animals %}
        {% set global_index = global_index + 1 %}
        <ul class="animal-data animal-{{ global_index }}" data-animal="{{animal.name}}">
            <ul>
                <li>Prénom :</li>
                <li>{{ animal.name }}</li>
            </ul>
            <ul>
                <li>Race :</li>
                <li>{{ animal.species }}</li>
            </ul>
            <ul>
                <li>Habitat :</li>
                <li>{{ habitat.name }}</li>
            </ul>
            <ul>
                {% for exam in animal.exams %}
                    <li>État :</li>
                    <li>{{ exam.state }}</li>
                {% endfor %}
            </ul>
            <ul>
                {% for exam in animal.exams %}
                    <li>Nourriture :</li>
                    <li>{{ exam.food }}</li>
                {% endfor %}
            </ul>
        </ul>
    {% endfor %}
{% endfor %}


</ul>

{% endblock %}


  {# <ul>
    {% for animal in habitat.animals %}
      <li>
        {{ animal.name }}
      </li>
    {% endfor %}
  </ul> #}

templates/components/adminList/firstItem.html.twig
{% block firstItem %}

<h2>Créer un compte</h2>
  {# Affichage des messages flash #}
  {% for message in app.flashes('success') %}
    <div class="alert alert-success">
      {{ message }}
    </div>
  {% endfor %}

  {# CREATE ACCOUNT FORM #}
  {{ form_start(form) }}
    {{ form_row(form.email) }}
      <div class="containerForm">
        <div>
          <label>{{ form_label(form.roles) }}</label>
        </div>
      <div>

      {% for choice in form.roles %}
        <div class="radio-wrapper">
          {{ form_widget(choice) }}
          {{ form_label(choice) }}
        </div>
      {% endfor %}
          
          </div>
          </div>
      <input value="Envoyer" type="submit" class="btn-submit"/>
  {{ form_end(form) }}

{% endblock %}

templates/components/adminList/fourthItem.html.twig
{% block fourthItem %}
<h2>Habitats</h2>
<ul>
{% for habitat in habitats %}

    <details>
    <summary>
      {{ habitat.name }}
      <div class="cross-container" data-id={{ habitat.name}}>
        <span>&#10060;</span>
      </div>
    </summary>
    <p>{{ habitat.description }}</p>
    <p>{{ habitat.image }}</p>
  </details> 
{% endfor %}
</ul>
{{form_start(formhabitats)}}
  <h3>Ajouter</h3>
  {{ form_row(formhabitats.name) }}
  {{ form_row(formhabitats.description) }}
  {{ form_row(formhabitats.image) }}
  <input value="Envoyer" type="submit" class="btn-submit btn-habitats"/>
{{form_end(formhabitats)}}
{% endblock %}

templates/components/adminList/secondItem.html.twig
{% block secondItem %}
<h2>Services</h2>
<ul>
{% for service in services %}

    <details>
    <summary>
      {{ service.title }}
      <div class="cross-container" data-id={{ service.title}}>
        <span>&#10060;</span>
      </div>
    </summary>
    <p>{{ service.description }}</p>
    <p>{{ service.urlIcon }}</p>
  </details> 
{% endfor %}
</ul>
{{form_start(formServices)}}
  <h3>Ajouter un nouveau service</h3>
  {{ form_row(formServices.title) }}
  {{ form_row(formServices.description) }}
  {{ form_row(formServices.url_icon) }}
  <input value="Envoyer" type="submit" class="btn-submit btn-services"/>
{{form_end(formServices)}}
{% endblock %}

templates/components/adminList/thirdItem.html.twig
{% block thirdItem %}

<h2>Horaires</h2>

{{ form_start(formHours) }}

  {{ form_row(formHours.jour) }}
  {{ form_row(formHours.openingHours) }}
  {{ form_row(formHours.closingHours) }}
  {{ form_row(formHours.ferme) }}
  <input value="Envoyer" type="submit" class="btn-submit"/>

{{ form_end(formHours) }}

{# Afficher les messages flash #}

{% for message in app.flashes('success') %}
  <div class="alert alert-success">
    {{ message }}
  </div>
  
{% endfor %}

{% endblock %}